production:
  ignore_errors:
    - ActiveRecord::RecordNotFound
    - ActionController::RoutingError
    - ActiveRecord::QueryCanceled
    - Rack::Timeout::RequestTimeoutException
    - Faraday::ConnectionFailed 
    - PackageURL::InvalidPackageURL
    - Faraday::SSLError
    - Rack::Timeout::RequestExpiryError
    - Faraday::TimeoutError
    - Oj::ParseError
    - Pagy::VariableError
    - Pagy::OverflowError 
    - ActiveRecord::StatementInvalid
    - SignalException
    - ActionController::UnknownFormat
    - ActionController::BadRequest
    - ActionDispatch::Http::MimeNegotiation::InvalidType
    - ActionDispatch::RemoteIp::IpSpoofAttackError